server:
  port: 9095
  servlet:
    session:
      timeout: 1h
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ## redirection http 현상 제거 ##
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml
spring:
  application:
    name: NANURI IT Corp STO PROJECT
  datasource:
    url: jdbc:log4jdbc:mariadb://172.30.1.42:3306/sto
    username: root
    password: sksnflIT1!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant-path-matcher

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729
      
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 2000MB
